# Basic Black and White QR Code generated by this code.
# import qrcode as qr

# img = qr.make("https://www.youtube.com/")
# img.save("Youtube.png")



# Advance QR Code Generator

import qrcode
from PIL import Image

qr = qrcode.QRCode(
    version = 1,
    error_correction = qrcode.constants.ERROR_CORRECT_H,
    box_size = 10, 
    border = 4
    )

qr.add_data("https://gyankarocket.blogspot.com")
qr.make(fit = True)
img = qr.make_image(fill_color = "red", back_color = "yellow")

img.save("My_Website.png")





